Make Radars Great Again (MRGA)
Qbox-project/qbx-policejob pull request #13
Opened 2023-04-26 01:13 UTC by TonybynMp4

## Description

Radars weren't that useful :c
now they really are radars (even if the file is called ANPR wich isn't really a radar i guess but who cares)

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2023-04-26 06:05 UTC, FjamZoo commented on server/main.lua
> +    exports['qbx-management']:AddMoney('police', price)
At the VERY least, we need to make sure that the PLAYER MONEY, is removed before we add Police Money to management

2023-04-26 06:06 UTC, TonybynMp4 commented on server/main.lua
> +    exports['qbx-management']:AddMoney('police', price)
true

2023-04-26 10:44 UTC, BerkieBb requested changes

2023-04-26 10:44 UTC, BerkieBb commented on client/anpr.lua
> +	if cache.vehicle and cache.seat == -1 and GetVehicleClass(cache.vehicle) ~= 18 then
invert if statement to return instead of wrapping all code in an if statement

2023-04-26 10:44 UTC, BerkieBb commented on client/anpr.lua
> +			HandlespeedCam(self, _)
an underscore is unusual, just make it k

2023-04-26 10:44 UTC, BerkieBb commented on client/anpr.lua
> +			coords = vec3(value.coords.x, value.coords.y, value.coords.z),
Instead of making a new vector3, you can also use `value.coords.xyz`, that returns the vector3 of the vector4

2023-04-26 11:00 UTC, TonybynMp4 commented on client/anpr.lua
> +			HandlespeedCam(self, _)
unusual ? it's in every resource

2023-04-27 19:38 UTC, BerkieBb approved these changes

2023-04-27 19:38 UTC, BerkieBb commented
Now to avoid these, you just have to have 0 money

2023-04-27 19:56 UTC, TonybynMp4 commented
> Now to avoid these, you just have to have 0 money

we need Qbx debt
(i don't think the bank goes below 0?)

2023-04-27 21:24 UTC, FjamZoo approved these changes

2023-04-27 21:25 UTC, merged