bugfixes: camera coords, camera id on alerts, alert coords, bloodDNA label
Qbox-project/qbx-policejob pull request #36
Opened 2023-08-03 02:03 UTC by buddizer

## Description

- Corrected all cameras to default GTA 5 stores (room for improvement)
- Added camera ID to store robbery police alerts
- Fixed incorrect alert coords on map
- Corrected bloodDNA label

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2023-08-03 06:38 UTC, Manason requested changes

2023-08-03 06:38 UTC, Manason commented on client/main.lua
> +        lib.notify({ title = text, description = street1name.. ' ' ..street2name.. '- Camera ID: ' .. camId, type = 'inform' })
Use a locale for 'Camera ID'?

2023-08-03 06:38 UTC, Manason commented on server/main.lua
> +        if isLeoAndOnDuty(v) and not camId then
This might be more readable if written as
```lua
if isLeoAndOnDuty(v) then
  if camId then
    ...
  else
    ...
  end
end

```

2023-08-03 06:38 UTC, Manason commented on server/main.lua
> +RegisterNetEvent('police:server:policeAlert', function(text, camId, source)
source should be an implied parameter. If this source is not the source of the event, it should be renamed to be more descriptive.

2023-08-03 20:30 UTC, buddizer commented on server/main.lua
> +RegisterNetEvent('police:server:policeAlert', function(text, camId, source)
How about now with playerSource?

2023-08-03 20:52 UTC, Manason commented on server/main.lua
> +RegisterNetEvent('police:server:policeAlert', function(text, camId, source)
Is source not the client calling the event?

2023-08-04 00:47 UTC, buddizer commented on server/main.lua
> +RegisterNetEvent('police:server:policeAlert', function(text, camId, source)
It is, although when I tested using the existing code (local src = source) on the server end, it would not return the data correctly, hence why I passed the source from the client and  the location was updated successfully.

2023-08-04 03:04 UTC, Manason commented on server/main.lua
> +RegisterNetEvent('police:server:policeAlert', function(text, camId, source)
That's probably because this event also gets called from the server https://github.com/Qbox-project/qbx-storerobbery/blob/d43d393e1d8e249adec50d122766aa2a28f52d62/server.lua#L36

I think a good refactor would be to extract a function that this event calls so that this event is not being triggered from both client and server.

2023-08-05 12:21 UTC, merged